<package format="3">
  <name>rk_tools</name>
  <version>0.0.1</version>
  <description>Mock hardware tools for the RK inspection robot.</description>
  <maintainer email="2605128876@qq.com">ZhenLi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rk_interfaces</exec_depend>
  <exec_depend>rk_mission</exec_depend>
  <exec_depend>rk_navigation</exec_depend>
  <exec_depend>rk_safety</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
