<package format="3">
  <name>rk_go2_sdk_bridge</name>
  <version>0.0.1</version>
  <description>Unitree Go2 SDK2 direct tools and deterministic UDP motion bridge.</description>
  <maintainer email="2605128876@qq.com">ZhenLi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>python3-opencv</depend>
  <depend>python3-numpy</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
