real_line_tracker_node:
  ros__parameters:
    image_topic: /camera/camera/color/image_raw
    line_track_topic: /perception/line_track
    enable_debug_image: false
    debug_log: false
    roi_top_fraction: 0.5
    threshold_value: 80
    min_contour_area: 300.0
    max_lateral_error: 1.0
    min_confidence_area: 1500.0
    frame_id: d435i_color_optical_frame
