<package format="3">
  <name>rk_interfaces</name>
  <version>0.0.1</version>
  <description>ROS2 interfaces for inspection robot</description>

  <maintainer email="2605128876@qq.com">ZhenLi</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>
</package>
